"""Some nullable columns

Revision ID: 10adbd5cf834
Revises: 651b57ce4d54
Create Date: 2021-05-18 22:42:04.130577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10adbd5cf834'
down_revision = '651b57ce4d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deputado', 'uri',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('deputado', 'siglaPartido',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('deputado', 'uriPartido',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('deputado', 'urlFoto',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deputado', 'urlFoto',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('deputado', 'uriPartido',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('deputado', 'siglaPartido',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('deputado', 'uri',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
