"""Nova colunas na tabela deputado

Revision ID: 41b0b7f16696
Revises: 8308b1fc47ed
Create Date: 2021-05-18 21:59:43.087685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b0b7f16696'
down_revision = '8308b1fc47ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputado', sa.Column('uri', sa.Text(), nullable=True))
    op.add_column('deputado', sa.Column('siglaPartido', sa.String(length=50), nullable=True))
    op.add_column('deputado', sa.Column('uriPartido', sa.Text(), nullable=True))
    op.add_column('deputado', sa.Column('siglaUf', sa.String(length=2), nullable=True))
    op.add_column('deputado', sa.Column('idLegislatura', sa.Integer(), nullable=True))
    op.add_column('deputado', sa.Column('urlFoto', sa.Text(), nullable=True))
    op.add_column('deputado', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deputado', 'email')
    op.drop_column('deputado', 'urlFoto')
    op.drop_column('deputado', 'idLegislatura')
    op.drop_column('deputado', 'siglaUf')
    op.drop_column('deputado', 'uriPartido')
    op.drop_column('deputado', 'siglaPartido')
    op.drop_column('deputado', 'uri')
    # ### end Alembic commands ###
