"""Nova tabela despesa_deputado

Revision ID: 4684d26f91b2
Revises: 10adbd5cf834
Create Date: 2021-05-26 22:32:25.546476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4684d26f91b2'
down_revision = '10adbd5cf834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
