"""Nova colunas na tabela deputado

Revision ID: 651b57ce4d54
Revises: 41b0b7f16696
Create Date: 2021-05-18 22:03:06.851203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651b57ce4d54'
down_revision = '41b0b7f16696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
