"""first version

Revision ID: b4ff40312b16
Revises: eb134ddf3594
Create Date: 2021-05-12 22:17:15.814421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ff40312b16'
down_revision = 'eb134ddf3594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
