"""first version

Revision ID: eb134ddf3594
Revises: 8cfde413e621
Create Date: 2021-05-12 21:16:37.391272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb134ddf3594'
down_revision = '8cfde413e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
